/home/bz1030/.conda/envs/knee_localizer/lib/python3.6/site-packages/scipy/ndimage/interpolation.py:583: UserWarning: From scipy 0.13.0, the output shape of zoom() is calculated with round() instead of int() - for these inputs the size of the returned array has changed.
  "the returned array has changed.", UserWarning)
Traceback (most recent call last):
  File "/gpfs/data/denizlab/Users/bz1030/src/main.py", line 16, in <module>
    main(month)
  File "/gpfs/data/denizlab/Users/bz1030/src/main.py", line 12, in main
    save_dir='/gpfs/data/denizlab/Users/bz1030/data/OAI_processed/')
  File "/gpfs/data/denizlab/Users/bz1030/src/preprocessing.py", line 86, in read_dicome_and_process
    img, data, img_before = image_preprocessing(os.path.join(data_path, data_file))
  File "/gpfs/data/denizlab/Users/bz1030/src/utils.py", line 32, in image_preprocessing
    img = interpolate_resolution(data) # get fixed resolution
  File "/gpfs/data/denizlab/Users/bz1030/src/utils.py", line 69, in interpolate_resolution
    x = image_dicom[0x28, 0x30].value[0]
  File "/home/bz1030/.conda/envs/knee_localizer/lib/python3.6/site-packages/pydicom/dataset.py", line 620, in __getitem__
    data_elem = self._dict[tag]
KeyError: (0028, 0030)
